# Best practice use list here
MATERIAL_BETON = 300
MATERIAL_BRICK = 500
MATERIAL_COMPOSITE = 800

# Districts
DISTRICT_CENTER = 1.7
DISTRICT_SLEEPING = 1.4
DISTRICT_SUBURB = 1.15

# Coef for floors
FLOOR_MIDDLE = 1.4
FLOORS_TOP_BOTTOM = 1.1

# Architecture styles
STYLE_HIGHTECH = 2
STYLE_EXCLUSIVE = 1.7
STYLE_INDIVIDUAL = 1.5
STYLE_STANDARD = 1.05

# Category indexes
CATEGORY_ELITE = 1.75
CATEGORY_BUDGET = 1.5
CATEGORY_PREFERENTIAL = 1.07